<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-may23/blob/main/may23_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = [1,3, 5, 2]

In [2]:
type(a)

list

In [3]:
for elem in a:
  print(elem**2)

1
9
25
4


In [4]:
b = [elem**2 for elem in a]

In [5]:
print(b)

[1, 9, 25, 4]


In [6]:
print(a)

[1, 3, 5, 2]


In [8]:
import numpy as np

In [9]:
a

[1, 3, 5, 2]

In [10]:
b = np.array(a)

In [11]:
print(b)

[1 3 5 2]


In [12]:
type(b) #numpy array

numpy.ndarray

In [13]:
type(a)

list

In [14]:
#np array vs python list

In [15]:
a = range(10000000)

In [16]:
len(a)

10000000

In [19]:
list(a[:5])

[0, 1, 2, 3, 4]

In [20]:
%timeit [ i**2 for i in a]

3.58 s ± 471 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
n1 = np.array(a)

In [22]:
len(n1)

10000000

In [23]:
type(n1)

numpy.ndarray

In [24]:
c = np.array([1,5,7,3])
print(c)

[1 5 7 3]


In [25]:
c + 5 #element-wise operation

array([ 6, 10, 12,  8])

In [26]:
%timeit n1**2

30.4 ms ± 1.53 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
type(n1)

numpy.ndarray

In [31]:
n1.ndim

1

In [29]:
n1.shape

(10000000,)

In [38]:
no_elem = n1.shape[0]
no_elem

10000000

In [32]:
a= [ [1,2,3] , [4,5,6] , [7,8,9], [3,5,1]]

In [33]:
b = np.array(a)

In [34]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 5 1]]


In [35]:
b.ndim

2

In [36]:
b.shape

(4, 3)

In [39]:
rows = b.shape[0]
cols = b.shape[1]

print(rows, cols)

4 3


In [40]:
r, c = b.shape
print(r,c)

4 3


In [42]:
b = np.arange(1,5)

In [43]:
type(b)

numpy.ndarray

In [44]:
print(b)

[1 2 3 4]


In [45]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [46]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
np.linspace(0,8,5)

array([0., 2., 4., 6., 8.])

In [48]:
4/2

2.0

In [50]:
b = np.array([4,5,7,6])
type(b)
b

array([4, 5, 7, 6])

In [51]:
b = np.array([4,5,7,6.5])
type(b)

numpy.ndarray

In [53]:
b

array([4. , 5. , 7. , 6.5])

In [54]:
a = [1, 2, 3, "AJ"]

In [55]:
b = np.array(a)
b

array(['1', '2', '3', 'AJ'], dtype='<U21')

In [56]:
np.array([1,2,3,4], dtype = "float")

array([1., 2., 3., 4.])

In [57]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [58]:
np.array(["Deepak", "Aditya" , "Kunal"], dtype = "float")

ValueError: ignored

In [59]:
c = np.array([1, 5, 7.6] , dtype = "int")
print(c)

[1 5 7]


In [62]:
c.dtype

dtype('int64')

In [63]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [64]:
type(a)

numpy.ndarray

In [65]:
a[0]

0

In [66]:
a[3]

3

In [67]:
a[-1]

11

In [68]:
a[-2]

10

In [70]:
b = a[:5]

In [71]:
type(b)

numpy.ndarray

In [72]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
a[-5:-1]

array([ 7,  8,  9, 10])

In [74]:
#masking

In [75]:
b = a + 2
print(b)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [76]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
b = a < 6

In [78]:
print(b)

[ True  True  True  True  True  True False False False False False False]


In [79]:
c = a[ a<6 ]

In [80]:
print(c)

[0 1 2 3 4 5]


In [81]:
#filter all the even elements using masking

In [82]:
a[ a%2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [83]:
#multi-indexing

In [84]:
a[0]

0

In [85]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [86]:
a[7]

8

In [87]:
a[5]

6

In [88]:
a[ [7, 5] ]

array([8, 6])

In [89]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
print(a[ [2, 6, 5] ])

[3 7 6]


In [91]:
#solving the NPS problem

In [92]:
score = np.loadtxt("survey.txt", dtype = "int")

In [93]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [94]:
print(score)

[ 7 10  5 ...  5  9 10]


In [95]:
len(score)

1167

In [96]:
score.shape

(1167,)

In [97]:
score.ndim

1

In [98]:
d_rating = score[ score < 7 ]
d_rating

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [99]:
detractors_count = len(d_rating)
detractors_count

332

In [100]:
p_rating = score[ score > 8 ]
p_rating

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [101]:
promoters_count = len(p_rating)
promoters_count

609

In [102]:
total_users = len(score)

In [103]:
total_users

1167

In [104]:
percent_promoters = (promoters_count/total_users)*100
percent_promoters

52.185089974293064

In [105]:
percent_detractors = (detractors_count/total_users)*100
percent_detractors

28.449014567266495

In [106]:
#HW - check how many neutrals we have

In [107]:
nps_score= percent_promoters - percent_detractors
nps_score

23.73607540702657

In [109]:
np.round(nps_score, 2)

23.74

In [110]:
#find the lowest rating in the survey

score.min()

1

In [111]:
np.min(score)

1

In [112]:
#highest rating in the survey
score.max()

10

In [113]:
#resource --> NPS industry wise