<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-may23/blob/main/may23_numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
1D --> vector
2D --> Matrix
3D --> Tensor
'''

'\n1D --> vector\n2D --> Matrix\n3D --> Tensor\n'

In [ ]:
import numpy as np

In [ ]:
a = np.arange(24).reshape(4,6)

In [ ]:
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
b = np.arange(24).reshape(2,3,4) #create two 2D matrices, each of size 3x4
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b[0][0]

array([0, 1, 2, 3])

In [ ]:
b[1][2]

array([20, 21, 22, 23])

In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[0][1][3]

7

In [ ]:
b[0,0]

array([0, 1, 2, 3])

In [ ]:
d = np.arange(30).reshape(5,2,3)

In [ ]:
print(d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]]


In [ ]:
#copy

In [ ]:
#shallow copy --> same address
#deep copy --> different address

In [ ]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [ ]:
b = a.reshape(2,2)
print(b)

[[0 1]
 [2 3]]


In [ ]:
print(a)


[0 1 2 3]


In [ ]:
a[0]= 11

In [ ]:
print(a)

[11  1  2  3]


In [ ]:
print(b)

[[11  1]
 [ 2  3]]


In [ ]:
np.shares_memory(a,b) #shallow copy

True

In [ ]:
print(a)

[11  1  2  3]


In [ ]:
c = a #shallow copy

In [ ]:
print(c)

[11  1  2  3]


In [ ]:
a[0] = 7

In [ ]:
print(a)

[7 1 2 3]


In [ ]:
print(c)

[7 1 2 3]


In [ ]:
c[1] = 99

In [ ]:
print(c)

[ 7 99  2  3]


In [ ]:
print(a)

[ 7 99  2  3]


In [ ]:
np.shares_memory(a,c)

True

In [ ]:
#case2

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
b = a[::2]
print(b)

[0 2 4 6 8]


In [ ]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(b)

[0 2 4 6 8]


In [ ]:
np.shares_memory(a,b)

True

In [ ]:
a[0] = 100

In [ ]:
print(a)

[100   1   2   3   4   5   6   7   8   9]


In [ ]:
print(b)

[100   2   4   6   8]


In [ ]:
a[4] = 200

In [ ]:
print(a)

[100   1   2   3 200   5   6   7   8   9]


In [ ]:
print(b)

[100   2 200   6   8]


In [ ]:
a[5] = 500

In [ ]:
print(a)

[100   1   2   3 200 500   6   7   8   9]


In [ ]:
print(b)

[100   2 200   6   8]


In [ ]:
a = np.arange(5)

In [ ]:
print(a)

[0 1 2 3 4]


In [ ]:
c = a.view() #shallow copy -- another syntax --> c = a

In [ ]:
np.shares_memory(a,c)

True

In [ ]:
a[0] = 9

In [ ]:
print(a)

[9 1 2 3 4]


In [ ]:
#deep copy --> .copy()

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
copy_a = a.copy() #create a deep copy
print(copy_a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.shares_memory(a, copy_a)

False

In [ ]:
a[1] = 100

In [ ]:
print(a)

[  0 100   2   3   4   5   6   7   8   9]


In [ ]:
print(copy_a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.array([1, "m"])
print(a)

['1' 'm']


In [ ]:
a = np.array([1, "m", [2, 3, 4]])

<ipython-input-64-29754f59d1c7>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([1, "m", [2, 3, 4]])


In [ ]:
a.dtype

dtype('O')

In [ ]:
a = np.array([1, "m", [2, 3, 4]], dtype = "object")

In [ ]:
b = a.copy()

In [ ]:
np.shares_memory(a,b)

False

In [ ]:
a[2][1] = 5

In [ ]:
print(a)

[1 'm' list([2, 5, 4])]


In [ ]:
print(b)

[1 'm' list([2, 5, 4])]


In [ ]:
a[2][2] = -1
print(a)

[1 'm' list([2, 5, -1])]


In [ ]:
print(b)

[1 'm' list([2, 5, -1])]


In [ ]:
import copy

In [ ]:
a = np.array([1, "m", [2,3,4]], dtype = "object")
print(a)

[1 'm' list([2, 3, 4])]


In [ ]:
copy_a = copy.deepcopy(a)

In [ ]:
a[2][1] = 100
print(a)

[1 'm' list([2, 100, 4])]


In [ ]:
print(copy_a)

[1 'm' list([2, 3, 4])]


In [ ]:
#concatenate

In [ ]:
a = np.array([2,4])
print(a)

[2 4]


In [ ]:
a.shape

(2,)

In [ ]:
a = np.array([[2,4]])
print(a)

[[2 4]]


In [ ]:
a.shape

(1, 2)

In [ ]:
b = np.concatenate((a,a), axis = 0)
print(b)

[[2 4]
 [2 4]]


In [ ]:
b = np.concatenate((a,a), axis = 1)
print(b)

[[2 4 2 4]]


In [ ]:
#stacking --> vstack, hstack

In [ ]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [ ]:
b = np.vstack([a,a,a])
print(b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
a = np.arange(5)
b = np.arange(5,10)
print(a,b)

[0 1 2 3 4] [5 6 7 8 9]


In [ ]:
c = np.vstack([a,b])
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
d = np.arange(6)
print(d)

[0 1 2 3 4 5]


In [ ]:
c = np.vstack([a,b,d])
print(c)

ValueError: ignored

In [ ]:
#horizontal stacking

In [ ]:
a = np.arange(5)
b = np.arange(5,10)
print(a,b)

[0 1 2 3 4] [5 6 7 8 9]


In [ ]:
np.hstack([a,b])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
d = np.arange(7)
print(d)

[0 1 2 3 4 5 6]


In [ ]:
np.hstack([a,b,d])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [ ]:
#HW--> try to check hstack for a 5x1 matrix

In [ ]:
#Splitting

In [ ]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [ ]:
b = np.split(a,3) #split a into 3 equal parts
print(b)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
print(b[0])

[0 1 2]


In [ ]:
c = np.split(a,4)

ValueError: ignored

In [ ]:
print(a)

[0 1 2 3 4 5 6 7 8]


In [ ]:
d = np.split(a, [2, 4, 5])
print(d)

[array([0, 1]), array([2, 3]), array([4]), array([5, 6, 7, 8])]


In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
d = np.split(a, [3,5,6])
print(d)

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]


In [ ]:
a = np.arange(4,10)
print(a)

[4 5 6 7 8 9]


In [ ]:
e = np.split(a, [2,4])
print(e)

[array([4, 5]), array([6, 7]), array([8, 9])]


In [ ]:
f = np.split(a, [2])

In [ ]:
print(f)

[array([4, 5]), array([6, 7, 8, 9])]


In [ ]:
#2d

In [ ]:
#hsplit--> split the horizontal axis (column-wise splitting)

In [ ]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(a, [1,2])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
#vsplit--> split the vertical axis

In [ ]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.vsplit(a,3)

ValueError: ignored

In [ ]:
b = np.vsplit(a, [1,2])

In [ ]:
type(b)

list